# Generated by Django 4.2.10 on 2025-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='pagado',
        ),
        migrations.AddField(
            model_name='venta',
            name='es_fiado',
            field=models.BooleanField(default=False),
        ),
    ]
