# Generated by Django 4.2.10 on 2025-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_monto_abonado_alter_venta_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_ultimo_abono',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
