# Generated by Django 4.2.10 on 2025-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_fecha_ultimo_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
