# Generated by Django 4.2.10 on 2025-06-18 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_proveedor_producto_stock_minimo'),
        ('clientes', '0002_cliente_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clientes.fiado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Fiado',
                'verbose_name_plural': 'Detalles de Fiados',
            },
        ),
    ]
