# Generated by Django 4.2.10 on 2025-06-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_detallefiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefiado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('abonado', 'Abonado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='detallefiado',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallefiado',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
