# Generated by Django 4.2.10 on 2025-06-21 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_detallefiado_estado_detallefiado_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiado',
            name='monto_abonado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fiado',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
