# Generated by Django 4.2.10 on 2025-06-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='almacen',
            name='estado',
            field=models.CharField(default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
