# Generated by Django 4.2.10 on 2025-06-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_alter_almacen_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='estado',
        ),
    ]
